# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373


MAILGUN_SMTP_LOGIN: posdtmaster@app7bef40cb07b847ab82128f8bb0ff56d6.mailgun.org
MAILGUN_SMTP_PASSWORD: 5424aab28042e3d73a1ac1d84c3c493f

production:
  STRIPE_SECRET_KEY: sk_live_1SzfXjia2mxK3ZVAptaDKJzO
  STRIPE_PUBLISHABLE_KEY: pk_live_CbWOCiip7gY1PrWLufSnTKBx
development:
  STRIPE_SECRET_KEY: sk_test_W3eCXVnHzn8vMWBRpcQoQQbD
  STRIPE_PUBLISHABLE_KEY: pk_test_kh5UpNIwWZvUDgLL50cfxZGt
