# Add configuration values here, as shown below.
#
# pusher_app_id: 
# pusher_key:
# pusher_secret:


MAILGUN_SMTP_LOGIN: 
MAILGUN_SMTP_PASSWORD: 

production:
  STRIPE_SECRET_KEY: 
  STRIPE_PUBLISHABLE_KEY: 
development:
  STRIPE_SECRET_KEY: 
  STRIPE_PUBLISHABLE_KEY: 
